# Generated by Django 5.1.5 on 2025-01-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_userscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='total_questions',
            field=models.IntegerField(default=10),
        ),
    ]
